version: '3.4'

services:
  app:
    environment:
      PORT: 8000
    restart: always
    container_name: app-axdd-components
    build:
      context: .
      target: app-container
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
